### TensorFlow works around 3 main components:

* Graph
* Tensor
* Session

Components|Descritption
---|---
Tensor|A tensor represents the data that progress between operations. 
Graph | All of the mathematical operations are performed inside a graph. You can <br>imagine a graph as a project where every operations are done.<br> The nodes represent these ops, they can absorb or create new tensors.
Session|A session will execute the operation from the graph.<br> To feed the graph with the values of a tensor, you need to open a session. <br>Inside a session, you must run an operator to create an output.


# Introduction to Tensors

### What is a Tensor?
Tensorflow's name is directly derived from its core framework: Tensor. In Tensorflow, all the computations involve tensors. A tensor is a vector or matrix of n-dimensions that represents all types of data. All values in a tensor hold identical data type with a known (or partially known) shape. The shape of the data is the dimensionality of the matrix or array.

A tensor can be originated from the input data or the result of a computation. In TensorFlow, all the operations are conducted inside a graph. The graph is a set of computation that takes place successively. Each operation is called an op node and are connected to each other.

The graph outlines the ops and connections between the nodes. However, it does not display the values. The edge of the nodes is the tensor, i.e., a way to populate the operation with data.

In Machine Learning, models are feed with a list of objects called feature vectors. A feature vector can be of any data type. The feature vector will usually be the primary input to populate a tensor. These values will flow into an op node through the tensor and the result of this operation/computation will create a new tensor which in turn will be used in a new operation. All these operations can be viewed in the graph.

### Representation of a Tensor

In TensorFlow, a tensor is a collection of feature vectors (i.e., array) of n-dimensions. For instance, if we have a 2x3 matrix with values from 1 to 6, we write:

![./images/tensor.png](./images/tensor.png)

TensorFlow represents this matrix as:


In [1]:

[[1, 2, 3], 
 [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

![./images/tensor3d.png](./images/tensor3d.png)


In [2]:
[[[1, 2, 3], 
 [4, 5, 6]],
 [[1, 2, 3], 
 [4, 5, 6]]]

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

## Parts of a tensor 
In TensorFlow, all the computations pass through one or more tensors. A tensor is an object with three properties:

* A unique label (name)
* A dimension (shape)
* A data type (dtype)

## Types of Tensor
Each operation you will do with TensorFlow involves the manipulation of a tensor. There are four main tensors you can create:

* tf.Variable
* tf.constant
* tf.placeholder
* tf.SparseTensor   

We will look at how to create a tf.constant and a tf.Variable.


## Constants

### Create a tensor of n-dimension


You begin with the creation of a tensor with one dimension, namely a scalar.

To create a tensor, you can use tf.constant()

In [2]:
# Import tf
import tensorflow as tf

In [3]:
r1 = tf.constant(1,tf.int16)
print(r1)

Tensor("Const:0", shape=(), dtype=int16)


In [4]:
## rank 0
# Default name
r1 = tf.constant(1, tf.int16) 
print(r1)

Tensor("Const_1:0", shape=(), dtype=int16)


![./images/tensorflowVariable.png](./images/tensorflowVariable.png)

### Creating Tensors of decimal and String types

In [5]:
# Decimal
r1_decimal = tf.constant(1.11, tf.float32)
print(r1_decimal)

Tensor("Const_2:0", shape=(), dtype=float32)


In [6]:
# String 
r1_String = tf.constant("hello world",tf.string)
print(r1_String)

Tensor("Const_3:0", shape=(), dtype=string)


### Create a vector 

In [7]:
r1_vector = tf.constant([2,3,4],tf.int16)
print(r1_vector)

Tensor("Const_4:0", shape=(3,), dtype=int16)


In [8]:
r1_boolean = tf.constant([True,False,True],tf.bool)
print(r1_boolean)

Tensor("Const_5:0", shape=(3,), dtype=bool)


### Create a 2d vector

In [9]:
r_2dVector = tf.constant([[2,3,5,6],[1,2,3,1]],tf.int16)
print(r_2dVector)

Tensor("Const_6:0", shape=(2, 4), dtype=int16)


In [33]:
two2darray=[[1,2],[3,4]]
r_2dVector2 = tf.constant(two2darray,tf.int16)
print(r_2dVector2)

Tensor("Const_15:0", shape=(2, 2), dtype=int16)


### Create a 3d vector 

In [11]:
threeDvector = [[[1,2,1],[3,4,4]],[[1,2,1],[2,3,4]]]

r_3dVector = tf.constant(threeDvector,tf.int16)
print(r_3dVector)

Tensor("Const_8:0", shape=(2, 2, 3), dtype=int16)


## View the Shpae of a Tensor

In [13]:
print(r_3dVector.shape)

(2, 2, 3)


In [14]:
r_3dVector.shape

TensorShape([Dimension(2), Dimension(2), Dimension(3)])

### Create Tensorflow of Zeros

In [15]:
r_zeros = tf.zeros(10)
print(r_zeros)
print(r_zeros.shape)

Tensor("zeros_1:0", shape=(10,), dtype=float32)
(10,)


In [16]:
print(tf.zeros([10,10]))

Tensor("zeros_1:0", shape=(10, 10), dtype=float32)


### Create Tensorflow of Ones

In [17]:
r_ones = tf.ones(2)
print(r_ones)

Tensor("ones:0", shape=(2,), dtype=float32)


In [18]:
r_ones_2 = tf.ones([2,2])
print(r_ones_2)
print(r_ones_2.shape)

Tensor("ones_1:0", shape=(2, 2), dtype=float32)
(2, 2)


## Tensor Operators

### Commonly used Tensorflow Operations
* tf.add(a, b)
* tf.substract(a, b)
* tf.multiply(a, b)
* tf.div(a, b)
* tf.pow(a, b)
* tf.exp(a)
* tf.sqrt(a)


#### Add tensor Objects

In [17]:
tensor_a = tf.constant([[1, 2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)

tensor_add = tf.add(tensor_a, tensor_b)
print(tensor_add)

Tensor("Add:0", shape=(1, 2), dtype=int32)


In [18]:
with tf.Session() as sess:
    print(sess.run(tensor_add))
    sess.close()


[[4 6]]


#### Multiply Tensors

In [19]:
tensor_a = tf.constant([[1],[2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)

tensor_mul = tf.multiply(tensor_a, tensor_b)
print(tensor_mul)



Tensor("Mul:0", shape=(2, 2), dtype=int32)


In [20]:
with tf.Session() as sess:
    print(sess.run(tensor_mul))
    sess.close()



[[3 4]
 [6 8]]


## Variables

So far, you have only created constant tensors. It is not of great use. Data always arrive with different values, to capture this, you can use the Variable class. It will represent a node where the values always change.

To create a variable, you can use tf.get_variable() method

In [23]:
# Create a Variable
## Create 2 Randomized values
var3 = tf.get_variable("var3", [1, 2])
print(var3.shape)

Instructions for updating:
Colocations handled automatically by placer.
(1, 2)


## Placeholder

A placeholder has the purpose of feeding the tensor. Placeholder is used to initialize the data to flow inside the tensors. To supply a placeholder, you need to use the method feed_dict. The placeholder will be fed only within a session.

In [25]:
A = tf.placeholder(tf.float32, shape=(None, 3))

In [24]:
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A: [[4, 5, 6], [7, 8, 9]]})
print(B_val_1)
#[[6. 7. 8.]]
print("New b.val_2")
print(B_val_2)
#[[9. 10. 11.]
sess.close()

[[6. 7. 8.]]
New b.val_2
[[ 9. 10. 11.]
 [12. 13. 14.]]


In [26]:
import numpy as np

In [27]:
x = tf.placeholder(tf.float32,(3,4))
y =  x + 2

sess = tf.Session()
#print(sess.run(y)) # will cause an error

s = np.random.rand(3,4)
print(sess.run(y, feed_dict={x:s}))

[[2.4237561 2.7212605 2.49685   2.6877985]
 [2.9708161 2.9696805 2.410176  2.3798256]
 [2.973372  2.5361886 2.190511  2.3664987]]


# Graph 

### a = (b+c)∗(c+2)
 . 

![./images/graphequations.png](./images/graphequations.png)

![./images/Simple-graph-example.png](./images/Simple-graph-example.png)

## Session


## Session

Graphs and sessions are independent. You can run a session and get the values to use later for further computations.

In the example below, you will:

* Create two tensors
* Create an operation
* Open a session
* Print the result


#### Step 1) You create two tensors x and y

In [26]:
## Create, run  and evaluate a session
x = tf.constant([3])
y = tf.constant([5])


#### Step 2) You create the operator by multiplying x and y

In [27]:
## Create operator
product= tf.multiply(x,y)


#### Step 3) You open a session. All the computations will happen within the session. When you are done, you need to close the session.

In [28]:
## Create a session to run the code
session = tf.Session()
output = session.run(product)
print(output)
session.close()


[15]


* **Code explanation**

    * tf.Session(): Open a session. All the operations will flow within the sessions
    * run(multiply): execute the operation created in step 2.
    * print(result_1): Finally, you can print the result
    * close(): Close the session

In [31]:
with tf.Session() as sess:
    result_2 = product.eval()
    print(result_2)


[15]


In [32]:
r2_matrix = tf.constant([ [1, 2],
                          [3, 4] ],tf.int16)
print(r2_matrix)

Tensor("Const_15:0", shape=(2, 2), dtype=int16)


In [33]:
r3_matrix = tf.constant([ [[1, 2],
                           [3, 4], 
                           [5, 6]] ], tf.int16)

In [34]:
## Check the tensors created before
sess = tf.Session()
print(sess.run(r1))
print(sess.run(r2_matrix))
print(sess.run(r3_matrix))

1
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]
  [5 6]]]


In [35]:
import numpy as np
data_placeholder_a =  tf.placeholder(tf.float32, name = "data_placeholder_a")
print(data_placeholder_a)			
power_a = tf.pow(data_placeholder_a, 2)
with tf.Session() as sess:  
    data = np.random.rand(1, 10)  
    print(sess.run(power_a, feed_dict={data_placeholder_a: data}))  # Will succeed.			

Tensor("data_placeholder_a:0", dtype=float32)
[[0.93364793 0.6776207  0.70156527 0.00120865 0.6772205  0.3523491
  0.01010027 0.8594502  0.27377546 0.02033965]]


In [36]:
import numpy as np
power_a = tf.pow(data_placeholder_a, 2)
with tf.Session() as sess:  
    data = np.random.rand(1, 10)  
    print(sess.run(power_a, feed_dict={data_placeholder_a: data}))  # Will succeed.	

[[0.14058417 0.42755687 0.02580318 0.984956   0.80113804 0.15445288
  0.31983665 0.6070638  0.39964858 0.8665181 ]]


In [37]:
x = tf.get_variable("x", dtype=tf.int32,  initializer=tf.constant([5]))
z = tf.get_variable("z", dtype=tf.int32,  initializer=tf.constant([6]))
c = tf.constant([5], name =	"constant")
square = tf.constant([2], name =	"square")
f = tf.multiply(x, z) + tf.pow(x, square) + z + c

### Code Explanation

* x: Initialize a variable called x with a constant value of 5
* z: Initialize a variable called z with a constant value of 6
* c: Initialize a constant tensor called c with a constant value of 5
* square: Initialize a constant tensor called square with a constant value of 2
* f: Construct the operator


In [38]:
init = tf.global_variables_initializer() # prepare to initialize all variables
with tf.Session() as sess:    
    init.run() # Initialize x and y    
    function_result = f.eval()
    print(function_result)

[66]


In [39]:
tf.reset_default_graph()  # To clear the default graph 

node1 = tf.constant(3.0, name="firstconst")
node2 = tf.constant(4.0, name="secondconst")
node3 = tf.add(node1, node2, name="sum")
node4 = tf.divide(node3, node1, name="sumdiv")

sess = tf.Session()
sess.run([node1, node2, node3, node4])

[3.0, 4.0, 7.0, 2.3333333]