In [2]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
tf.enable_eager_execution()
tfe = tf.contrib.eager

print(tf.__version__)

W0505 23:17:44.887274 140735952987008 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



1.14.0


In [3]:
dataset = tf.data.Dataset.range(10)
#print(dataset)
for val in dataset:
  print(val.numpy())


0
1
2
3
4
5
6
7
8
9


In [4]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1)
for window_dataset in dataset :
  for val in window_dataset:
    print(val.numpy(),end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [5]:
dataset

<DatasetV1Adapter shapes: <tensorflow.python.data.ops.dataset_ops.DatasetStructure object at 0x1a3f1de048>, types: <tensorflow.python.data.ops.dataset_ops.DatasetStructure object at 0x1a3f1de048>>

In [6]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
for window_dataset in dataset :
  for val in window_dataset:
    print(val.numpy(),end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [10]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window_dataset in dataset :
    print(window_dataset.numpy())


[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [6]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window:(window[:-1],window[-1:]))
for x,y  in dataset :
  print(x.numpy(),y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [7]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window:(window[:-1],window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y  in dataset :
  print(x.numpy(),y.numpy())

[4 5 6 7] [8]
[2 3 4 5] [6]
[1 2 3 4] [5]
[0 1 2 3] [4]
[5 6 7 8] [9]
[3 4 5 6] [7]


In [18]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window:(window[:-1],window[-1:]))
#dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2)
for x,y  in dataset :
  print("x = ", x.numpy())
  print("y = ", y.numpy())


x =  [[0 1 2 3]
 [1 2 3 4]]
y =  [[4]
 [5]]
x =  [[2 3 4 5]
 [3 4 5 6]]
y =  [[6]
 [7]]
x =  [[4 5 6 7]
 [5 6 7 8]]
y =  [[8]
 [9]]


In [19]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window:(window[:-1],window[-1:]))
#dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x,y  in dataset :
  print("x = ", x.numpy())
  print("y = ", y.numpy())

x =  [[0 1 2 3]
 [1 2 3 4]]
y =  [[4]
 [5]]
x =  [[2 3 4 5]
 [3 4 5 6]]
y =  [[6]
 [7]]
x =  [[4 5 6 7]
 [5 6 7 8]]
y =  [[8]
 [9]]
